//SETTINGS =====================================================================
VILLAGEMARKERSIZE = 200;
CITYMARKERSIZE = 300;
CAPITALMARKERSIZE = 400;
OTHERMARKERSIZE = 200;
BLUFORSPAWNDIST = 1200;
BLUFORSPAWNBAND = 1000;
OPFORRESPAWNDIST = 100;
CIVILIANPROBABILITY = 5;
DEALERRADIUSFACTOR = 0.75;																										//CITYAREASIZE * DEALERRADIUSFACTOR == DEALERSPAWNRADIUS
MAXRESPAWNTIME = 1000;
ISWOODLAND = (ISLAND_CONFIG select (ISLANDS find worldName)) select 0;

publicVariable "VILLAGEMARKERSIZE";
publicVariable "CITYMARKERSIZE";
publicVariable "CAPITALMARKERSIZE";
publicVariable "OTHERMARKERSIZE";
publicVariable "BLUFORSPAWNDIST";
publicVariable "BLUFORSPAWNBAND";
publicVariable "OPFORRESPAWNDIST";
publicVariable "CIVILIANPROBABILITY";
publicVariable "DEALERRADIUSFACTOR";
publicVariable "ISWOODLAND";


//OTHER ========================================================================
OPFORTELEPORTED = false;
BLUFORTELEPORTED = false;
GAMESTARTED = false;
GAMEENDED = false;
BLUFORINCONTROL = false;
BLUFORELIMINATED = false;
OPFORELIMINATED = false;
CITYCAPTURED = false;
CITYDEFENDED = false;
COMMANDVEHICLEDESTROYED = false;
CVININNER = false;
CVINOUTER = false;
CVACTIVE = false;
DEALERKILLED = false;
CIVSKILLEDBLU = 0;
CIVSKILLEDOPF = 0;
CAPTURETIMEREMAINING = CAPTURETIME;

publicVariable "OPFORTELEPORTED";
publicVariable "BLUFORTELEPORTED";
publicVariable "GAMESTARTED";
publicVariable "GAMEENDED";
publicVariable "BLUFORINCONTROL";
publicVariable "BLUFORELIMINATED";
publicVariable "OPFORELIMINATED";
publicVariable "CITYCAPTURED";
publicVariable "CITYDEFENDED";
publicVariable "COMMANDVEHICLEDESTROYED";
publicVariable "CVININNER";
publicVariable "CVINOUTER";
publicVariable "CVACTIVE";
publicVariable "DEALERKILLED";
publicVariable "CIVSKILLEDBLU";
publicVariable "CIVSKILLEDOPF";
publicVariable "CAPTURETIMEREMAINING";
